apiVersion: v1
kind: Pod
metadata:
  name: db-pets
  labels:
    app: db-pets
spec:
  containers:
    - name: db-pets-container
      image: souzaa00o/mysql_my_pets:1.0
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: db-pets-configmap
