apiVersion: v1
kind: Pod
metadata:
  name: web-server
  labels:
    app: web-server
spec:
  containers:
    - name: web-server-container
      image: nginx:stable
      ports:
        - containerPort: 80
